# Generated by Django 6.0.4 on 2026-04-11 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='pagada',
            new_name='esta_pagada',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='monto_capital',
            new_name='monto_solicitado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='monto_cuota',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cantidad_cuotas',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_pago_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cuotas_totales',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='frecuencia',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='mensual', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='score_interno',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='numero_cuota',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pagos', to='app_prestamos.prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='app_prestamos.cliente'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('activo', 'Activo'), ('mora', 'En Mora'), ('finalizado', 'Finalizado')], default='pendiente', max_length=15),
        ),
    ]
