# Generated by Django 6.0.4 on 2026-04-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0004_cliente_activo_prestamo_activo_historialestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_prestamos.cuota')),
            ],
        ),
    ]
