# Generated by Django 6.0.4 on 2026-06-02 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0005_historialcuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_prestamos.cuota'),
        ),
    ]
