# Generated by Django 6.0.4 on 2026-06-03 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0006_caja_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='app_prestamos.prestamo'),
        ),
    ]
