# Generated by Django 6.0.4 on 2026-06-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0007_alter_cuota_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='mora_pagada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
