# Generated by Django 6.0.4 on 2026-07-15 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0008_cuota_mora_pagada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('mora', 'En Mora'), ('finalizado', 'Finalizado')], default='activo', max_length=15),
        ),
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True, verbose_name='Fecha de Operación')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_apertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ingresos_sistema', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('egresos_sistema', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_real_fisico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios en caso de que haya diferencias', null=True)),
                ('operador_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('operador_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Diaria',
                'verbose_name_plural': 'Cajas Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='caja_diaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='app_prestamos.cajadiaria'),
        ),
    ]
