# Generated by Django 6.0.4 on 2026-07-22 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0009_alter_prestamo_estado_cajadiaria_caja_caja_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_prestamos.prestamo'),
        ),
    ]
