# Generated by Django 6.0.4 on 2026-07-22 19:41

import app_prestamos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0010_caja_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Recibo de sueldo, Título del auto, Fotos propiedad', max_length=150)),
                ('archivo', models.FileField(upload_to=app_prestamos.models.cliente_garantia_path)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='app_prestamos.cliente')),
            ],
        ),
    ]
