# Generated by Django 6.0.4 on 2026-07-25 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0011_garantiacliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
