# Generated by Django 6.0.4 on 2026-07-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0012_cuota_monto_pagado_alter_prestamo_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='cuota',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='efectivo', max_length=20),
        ),
    ]
