# Generated by Django 6.0.4 on 2026-08-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0013_caja_metodo_pago_cuota_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='metodo_pago',
            field=models.CharField(default='efectivo', help_text='Forma de pago pactada para el préstamo', max_length=50),
        ),
    ]
