# Generated by Django 6.0.4 on 2026-08-31 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0014_prestamo_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_crear_prestamo', models.BooleanField(default=True)),
                ('puede_cobrar_cuota', models.BooleanField(default=True)),
                ('puede_crear_cliente', models.BooleanField(default=True)),
                ('puede_editar_cliente', models.BooleanField(default=False)),
                ('puede_eliminar_cliente', models.BooleanField(default=False)),
                ('puede_ver_caja', models.BooleanField(default=False)),
                ('puede_ver_metricas', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_custom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
